[package]
name = "mini_bin_rus"
version = "0.1.0"
edition = "2024"

[dependencies]
tray-item = "0.10.0"
windows-sys = { version = "0.59", features = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[build-dependencies]
embed-resource = "2.3"
